apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-web
  labels:
    app: order-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-web
  template:
    metadata:
      labels:
        app: order-web
    spec:
      containers:
        - name: order-web
          image: udineshu/order-service:10
          command: [ "sleep" ]
          args: [ "infinity" ]
          ports:
            - containerPort: 8080
