apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-web-appsody
  labels:
    app: order-web-appsody
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-web-appsody
  template:
    metadata:
      labels:
        app: order-web-appsody
    spec:
      containers:
        - name: order-web-appsody
          image: udineshu/myprivaterepo:latest
          command: [ "sleep" ]
          args: [ "infinity" ]
          ports:
            - containerPort: 8081
